DROP TABLE IF EXISTS `customer_service_correspondence`;
--;;
DROP TABLE IF EXISTS `customer_group`;
--;;
DROP TABLE IF EXISTS `customer_form_attribute`;
--;;
DROP TABLE IF EXISTS `customer_address_entity_varchar`;
--;;
DROP TABLE IF EXISTS `customer_address_entity_text`;
--;;
DROP TABLE IF EXISTS `customer_address_entity_int`;
--;;
DROP TABLE IF EXISTS `customer_address_entity_decimal`;
--;;
DROP TABLE IF EXISTS `customer_address_entity_datetime`;
--;;
DROP TABLE IF EXISTS `customer_address_entity`;
--;;
DROP TABLE IF EXISTS `customer_entity_varchar`;
--;;
DROP TABLE IF EXISTS `customer_entity_text`;
--;;
DROP TABLE IF EXISTS `customer_entity_int`;
--;;
DROP TABLE IF EXISTS `customer_entity_decimal`;
--;;
DROP TABLE IF EXISTS `customer_entity_datetime`;
--;;
DROP TABLE IF EXISTS `customer_entity`;
