DELETE FROM `catalog_product_entity_varchar`;
--;;
DELETE FROM `cataloginventory_stock_status`;
--;;
DELETE FROM `cataloginventory_stock`;
--;;
DELETE FROM `catalog_product_website`;
--;;
DELETE FROM `catalog_product_super_link`;
--;;
DELETE FROM `catalog_product_entity`;
--;;
DELETE FROM `eav_attribute`;
--;;
DELETE FROM `eav_attribute_set`;
--;;
DELETE FROM `eav_entity_type`;
--;;
DELETE FROM `core_store`;
--;;
DELETE FROM `core_store_group`;
--;;
DELETE FROM `core_website`;
