DROP TABLE `core_variable_value`;
--;;
DROP TABLE `core_variable`;
--;;
DROP TABLE `core_translate`;
--;;
DROP TABLE `core_session`;
--;;
DROP TABLE `core_resource`;
--;;
DROP TABLE `core_layout_link`;
--;;
DROP TABLE `core_layout_update`;
--;;
DROP TABLE `core_flag`;
--;;
DROP TABLE `core_email_template`;
--;;
DROP TABLE `core_directory_storage`;
--;;
DROP TABLE `core_config_data`;
--;;
DROP TABLE `core_cache_tag`;
--;;
DROP TABLE `core_cache_option`;
--;;
DROP TABLE `core_cache`;
--;;
DROP TABLE `core_store`;
--;;
DROP TABLE `core_store_group`;
--;;
DROP TABLE `core_website`;
