DROP TABLE IF EXISTS `enterprise_admin_passwords`;
--;;
DROP TABLE IF EXISTS `adminnotification_inbox`;
--;;
DROP TABLE IF EXISTS `admin_user`;
--;;
DROP TABLE IF EXISTS `admin_rule`;
--;;
DROP TABLE IF EXISTS `admin_role`;
--;;
DROP TABLE IF EXISTS `admin_assert`;
