DROP TABLE `customer_eav_attribute_website`;
--;;
DROP TABLE `customer_eav_attribute`;
--;;
DROP TABLE `catalog_eav_attribute`;
--;;
DROP TABLE `eav_form_type_entity`;
--;;
DROP TABLE `eav_form_fieldset_label`;
--;;
DROP TABLE `eav_form_element`;
--;;
DROP TABLE `eav_form_fieldset`;
--;;
DROP TABLE `eav_form_type`;
--;;
DROP TABLE `eav_entity_varchar`;
--;;
DROP TABLE `eav_entity_text`;
--;;
DROP TABLE `eav_entity_store`;
--;;
DROP TABLE `eav_entity_int`;
--;;
DROP TABLE `eav_entity_decimal`;
--;;
DROP TABLE `eav_entity_datetime`;
--;;
DROP TABLE `eav_entity_attribute`;
--;;
DROP TABLE `eav_attribute_option_value`;
--;;
DROP TABLE `eav_attribute_option`;
--;;
DROP TABLE `eav_attribute_label`;
--;;
DROP TABLE `eav_attribute_group`;
--;;
DROP TABLE `eav_attribute_set`;
--;;
DROP TABLE `eav_attribute`;
--;;
DROP TABLE `eav_entity`;
--;;
DROP TABLE `eav_entity_type`;
