DROP TABLE IF EXISTS `catalog_product_website`;
--;;
DROP TABLE IF EXISTS `catalog_product_super_link`;
--;;
DROP TABLE IF EXISTS `catalog_product_super_attribute_pricing`;
--;;
DROP TABLE IF EXISTS `catalog_product_super_attribute_label`;
--;;
DROP TABLE IF EXISTS `catalog_product_super_attribute`;
--;;
DROP TABLE IF EXISTS `catalog_product_relation`;
--;;
DROP TABLE IF EXISTS `catalog_product_option_type_title`;
--;;
DROP TABLE IF EXISTS `catalog_product_option_type_price`;
--;;
DROP TABLE IF EXISTS `catalog_product_option_type_value`;
--;;
DROP TABLE IF EXISTS `catalog_product_option_title`;
--;;
DROP TABLE IF EXISTS `catalog_product_option_price`;
--;;
DROP TABLE IF EXISTS `catalog_product_option`;
--;;
DROP TABLE IF EXISTS `catalog_product_link_attribute_varchar`;
--;;
DROP TABLE IF EXISTS `catalog_product_link_attribute_int`;
--;;
DROP TABLE IF EXISTS `catalog_product_link_attribute_decimal`;
--;;
DROP TABLE IF EXISTS `catalog_product_link_attribute`;
--;;
DROP TABLE IF EXISTS `catalog_product_link`;
--;;
DROP TABLE IF EXISTS `catalog_product_link_type`;
--;;
DROP TABLE IF EXISTS `catalog_product_enabled_index`;
--;;
DROP TABLE IF EXISTS `catalog_product_bundle_stock_index`;
--;;
DROP TABLE IF EXISTS `catalog_product_bundle_selection_price`;
--;;
DROP TABLE IF EXISTS `catalog_product_bundle_selection`;
--;;
DROP TABLE IF EXISTS `catalog_product_bundle_price_index`;
--;;
DROP TABLE IF EXISTS `catalog_product_bundle_option_value`;
--;;
DROP TABLE IF EXISTS `catalog_product_bundle_option`;
--;;
DROP TABLE IF EXISTS `catalog_product_entity_varchar`;
--;;
DROP TABLE IF EXISTS `catalog_product_entity_url_key`;
--;;
DROP TABLE IF EXISTS `catalog_product_entity_tier_price`;
--;;
DROP TABLE IF EXISTS `catalog_product_entity_text`;
--;;
DROP TABLE IF EXISTS `catalog_product_entity_media_gallery_value`;
--;;
DROP TABLE IF EXISTS `catalog_product_entity_media_gallery`;
--;;
DROP TABLE IF EXISTS `catalog_product_entity_int`;
--;;
DROP TABLE IF EXISTS `catalog_product_entity_group_price`;
--;;
DROP TABLE IF EXISTS `catalog_product_entity_gallery`;
--;;
DROP TABLE IF EXISTS `catalog_product_entity_decimal`;
--;;
DROP TABLE IF EXISTS `catalog_product_entity_datetime`;
--;;
DROP TABLE IF EXISTS `catalog_product_entity`;
